FUNCTION STDELEM=STDARRAY(A,N)
    AVGELEM=AVGARRAY(A,N);
    STDELEM=0;
    FOR I=1:N
        STDELEM=STDELEM+((A(I)-AVGELEM)*(A(I)-AVGELEM));
    END
    STDELEM=SQRT(STDELEM/N);
END
