clc;
clear all;
close all;
file1=input('\n enter input image file name','s');
file2=input('\n enter output image file 1 name','s');
file3=input('\n enter output image file 2 name','s');
x=imread(file1);
[r,c,d]=size(x);
r1=fix(r/2);
y1(1:r1,1:c,1:d)=x(1:r1,1:c,1:d);
y2(1:r-r1,1:c,1:d)=x(r1+1:r,1:c,1:d);
imwrite(y1,file2);
imwrite(y2,file3);
imshow(y1);