#!/bin/sh
#To find the fibonacci number

a=0
b=1
echo -n "Enter the range upto which u want to print "
read n

echo -n $a" "$b" "
c=` expr $a + $b `
while [ $c -le $n ]
do
	echo -n $c" "
	a=$b
	b=$c
	c=` expr $a + $b `
	
done
