import pyttsx
engine = pyttsx.init()
#engine.say('Greetings!')
#engine.say('How are you today?')
#engine.runAndWait()
#engine.say('Hello I\'m Jimut\'s AI')
#engine.runAndWait()
engine.say('Amlyan is a hero ')
#engine.runAndWait()
#engine.say('Let\'s make AI shit after sem - 3')
#engine.runAndWait()
engine.say('Bakki ... sab zero')
#engine.runAndWait()
#engine.say('Sem - 4 will be fun ... hopefully')
engine.runAndWait()
