#!/bin/sh
clear
echo -n "Enter size of your list="
read n
echo "Enter $n elements one by one --->"
i=1
        while [ $i -le $n ]
        do
        echo -n "a[$i]="
        eval read a$i
        i=`expr $i + 1`
        done
clear
echo "Number"
i=1
        while [ $i -le $n ]
        do
        eval echo -n "   \$a$i   "
	echo "      "
        i=`expr $i + 1`
        done
sum=0
i=1
eval max=\$a$i
eval small=\$a$i

	i=1
        while [ $i -le $n ]
        do
	eval ai=\$a$i
		if [ $max -le $ai ]
		then
		max=$ai
		fi
         	if [ $small -ge $ai ]
		then
		small=$ai
		fi
	sum=`expr $sum + $ai`
	i=`expr $i + 1`
	done
avg=`expr $sum / $n`
echo -n
echo "Sum = $sum , average = $avg , largest number = $max, smallest number =$small"
#end
