#!/bin/sh
clear
echo -n "Enter size of your list="
read n
echo "Enter $n elements one by one --->"
i=1
        while [ $i -le $n ]
        do
        echo -n "a[$i]="
        eval read a$i
        i=`expr $i + 1`
        done
clear
echo "Number"
i=1
        while [ $i -le $n ]
        do
        eval echo -n "   \$a$i  "
        i=`expr $i + 1`
        done
echo " Sorted array : "
i=1
j=`expr $i + 1`
swap=0
	while [ $i -lt $((n-1)) ]
	do
	while [ $j -le $n ]
	do
	eval ai=\$a$i
	eval aj=\$a$j
	if [ $aj -lt $ai ]
	then
	swap=$aj
	eval a$j=$ai
	eval a$i=$swap
	fi
	j=`expr $j + 1`
	done
	i=`expr $i + 1` 
	done
echo  "Number"
i=1
        while [ $i -le $n ]
        do
        eval echo "   \$a$i  "
	echo "     "
        i=`expr $i + 1`
        done
#end
	
	

