#!/bin/sh
echo -n "Enter the no. of elements of array :"
read n
sum=0
i=1
while [ $i -le $n ]
do
	#codes
	echo "Enter the a[$i] element :"
	eval read a$i
	eval d=\$a$i
	sum=` expr $sum + $d ` 
	i=` expr $i + 1 `
done
echo "Sum is :"$sum
