clc;
close all;
clear all;
file1=input('Enter input file name=','s');
file2=input('Enter output file name=','s');
fp1=fopen(file1,'r');
fp2=fopen(file2,'w');
ch=fread(fp1);
fwrite(fp2,ch);
n=length(ch);
fprintf('\nNumber of bytes copied=%d\n',n);
fclose('all');